/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyCard {
        "name": string;
    }
    interface MyComponent {
    }
    interface SearchWord {
        "searchText": string;
    }
    interface SideMenu {
    }
}
export interface SearchWordCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSearchWordElement;
}
declare global {
    interface HTMLMyCardElement extends Components.MyCard, HTMLStencilElement {
    }
    var HTMLMyCardElement: {
        prototype: HTMLMyCardElement;
        new (): HTMLMyCardElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSearchWordElement extends Components.SearchWord, HTMLStencilElement {
    }
    var HTMLSearchWordElement: {
        prototype: HTMLSearchWordElement;
        new (): HTMLSearchWordElement;
    };
    interface HTMLSideMenuElement extends Components.SideMenu, HTMLStencilElement {
    }
    var HTMLSideMenuElement: {
        prototype: HTMLSideMenuElement;
        new (): HTMLSideMenuElement;
    };
    interface HTMLElementTagNameMap {
        "my-card": HTMLMyCardElement;
        "my-component": HTMLMyComponentElement;
        "search-word": HTMLSearchWordElement;
        "side-menu": HTMLSideMenuElement;
    }
}
declare namespace LocalJSX {
    interface MyCard {
        "name"?: string;
    }
    interface MyComponent {
    }
    interface SearchWord {
        "onSearchWordNameSelected"?: (event: SearchWordCustomEvent<string>) => void;
        "searchText"?: string;
    }
    interface SideMenu {
    }
    interface IntrinsicElements {
        "my-card": MyCard;
        "my-component": MyComponent;
        "search-word": SearchWord;
        "side-menu": SideMenu;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-card": LocalJSX.MyCard & JSXBase.HTMLAttributes<HTMLMyCardElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "search-word": LocalJSX.SearchWord & JSXBase.HTMLAttributes<HTMLSearchWordElement>;
            "side-menu": LocalJSX.SideMenu & JSXBase.HTMLAttributes<HTMLSideMenuElement>;
        }
    }
}
